### ISSUE TITLE
Default database link not working

### ISSUE THREAD

**Issue by gisleDK** [kiwiroy/deconseq#1]
Unable to connect to ftp://edwards.sdsu.edu:7009/deconseq/db/ and ftp://edwards.sdsu.edu:7009/deconseq
Default databases cannot be downloaded

**Comment by kiwiroy** [comment]
Sorry, I'm not the maintainer, this is only a source code mirror. Can you address [their](http://deconseq.sourceforge.net/index.html) [mailing list](https://groups.google.com/forum/#!forum/edwardslabtools)? It looks like this is a [known issue](https://groups.google.com/forum/#!topic/edwardslabtools/F8dOX39aJ3s).

**Comment by gisleDK** [comment]
Thanks for the fast reply.
